; **************************************************************************************************
; For usage with the 'Starting Soldiers' mod
; **************************************************************************************************
; ------------------------------------------------------------------------------
; G.I. Joe
; ------------------------------------------------------------------------------
[WOTCStartingSoldiers.X2DownloadableContentInfo_WOTCStartingSoldiers]
.CHARACTER_INFO=(SoldierName="Alvin Kibbey"                , SoldierClass="GIJoe__Breaker"              , SoldierRank=2)
.CHARACTER_INFO=(SoldierName="Lance Steinberg"             , SoldierClass="GIJoe__Clutch"               , SoldierRank=2)
.CHARACTER_INFO=(SoldierName="Anthony Gambello"            , SoldierClass="GIJoe__Flash"                , SoldierRank=2)
.CHARACTER_INFO=(SoldierName="James Barney"                , SoldierClass="GIJoe__Grand_Slam"           , SoldierRank=2)
.CHARACTER_INFO=(SoldierName="Robert Graves"               , SoldierClass="GIJoe__Grunt"                , SoldierRank=2)
.CHARACTER_INFO=(SoldierName="Clayton Abernathy"           , SoldierClass="GIJoe__Hawk"                 , SoldierRank=2)
.CHARACTER_INFO=(SoldierName="Craig McConnel"              , SoldierClass="GIJoe__Rock_n_Roll"          , SoldierRank=2)
.CHARACTER_INFO=(SoldierName="Eric Friestadt"              , SoldierClass="GIJoe__Short_Fuze"           , SoldierRank=2)
.CHARACTER_INFO=(SoldierName="Shana O'Hara"                , SoldierClass="GIJoe__Scarlett"             , SoldierRank=2)
.CHARACTER_INFO=(SoldierName="FILE G-8210 CLASSIFIED"      , SoldierClass="GIJoe__Snake_Eyes"           , SoldierRank=2)
.CHARACTER_INFO=(SoldierName="Lonzo Wilkinson"             , SoldierClass="GIJoe__Stalker"              , SoldierRank=2)
.CHARACTER_INFO=(SoldierName="Ralph Pulaski"               , SoldierClass="GIJoe__Steeler"              , SoldierRank=2)
.CHARACTER_INFO=(SoldierName="Rafael Melendez"             , SoldierClass="GIJoe__Zap"                  , SoldierRank=2)
.CHARACTER_INFO=(SoldierName="Jodie Craig"                 , SoldierClass="GIJoe__Shooter"              , SoldierRank=2)

; ------------------------------------------------------------------------------
; G.I. Joe Renegades
; ------------------------------------------------------------------------------
[WOTCStartingSoldiers.X2DownloadableContentInfo_WOTCStartingSoldiers]

; ------------------------------------------------------------------------------
; Battleforce 2000
; ------------------------------------------------------------------------------
[WOTCStartingSoldiers.X2DownloadableContentInfo_WOTCStartingSoldiers]

; ------------------------------------------------------------------------------
; G.I. Joe Ally
; ------------------------------------------------------------------------------
[WOTCStartingSoldiers.X2DownloadableContentInfo_WOTCStartingSoldiers]

; ------------------------------------------------------------------------------
; Arashikage
; ------------------------------------------------------------------------------
[WOTCStartingSoldiers.X2DownloadableContentInfo_WOTCStartingSoldiers]

; ------------------------------------------------------------------------------
; Oktober Guard
; ------------------------------------------------------------------------------
[WOTCStartingSoldiers.X2DownloadableContentInfo_WOTCStartingSoldiers]

; ------------------------------------------------------------------------------
; Cobra
; ------------------------------------------------------------------------------
[WOTCStartingSoldiers.X2DownloadableContentInfo_WOTCStartingSoldiers]

; ------------------------------------------------------------------------------
; M.A.R.S.
; ------------------------------------------------------------------------------
[WOTCStartingSoldiers.X2DownloadableContentInfo_WOTCStartingSoldiers]

; ------------------------------------------------------------------------------
; Dreadnoks
; ------------------------------------------------------------------------------
[WOTCStartingSoldiers.X2DownloadableContentInfo_WOTCStartingSoldiers]

; ------------------------------------------------------------------------------
; M.A.S.K.
; ------------------------------------------------------------------------------
[WOTCStartingSoldiers.X2DownloadableContentInfo_WOTCStartingSoldiers]

; ------------------------------------------------------------------------------
; V.E.N.O.M.
; ------------------------------------------------------------------------------
[WOTCStartingSoldiers.X2DownloadableContentInfo_WOTCStartingSoldiers]

; ------------------------------------------------------------------------------
; Danger Girl
; ------------------------------------------------------------------------------
[WOTCStartingSoldiers.X2DownloadableContentInfo_WOTCStartingSoldiers]

; ------------------------------------------------------------------------------
; Unaffiliated
; ------------------------------------------------------------------------------
[WOTCStartingSoldiers.X2DownloadableContentInfo_WOTCStartingSoldiers]

+bRemoveStartingSoldiers=true;
+bReplaceStartingSquad=true;
