; **************************************************************************************************
; Add Mod to game and prevent custom classes from rolling in random AWC
; **************************************************************************************************
[LWOTC_GIJoe.X2DownloadableContentInfo_LWOTC_GIJoe]
DLCIdentifier="LWOTC_GIJoe"

[XComGame.CHHelpers]
+ClassesExcludedFromAWCRoll=GIJoe__Breaker
+ClassesExcludedFromAWCRoll=GIJoe__Clutch
+ClassesExcludedFromAWCRoll=GIJoe__Flash
+ClassesExcludedFromAWCRoll=GIJoe__Grand_Slam
+ClassesExcludedFromAWCRoll=GIJoe__Grunt
+ClassesExcludedFromAWCRoll=GIJoe__Hawk
+ClassesExcludedFromAWCRoll=GIJoe__Rock_n_Roll
+ClassesExcludedFromAWCRoll=GIJoe__Short_Fuze
+ClassesExcludedFromAWCRoll=GIJoe__Scarlett
+ClassesExcludedFromAWCRoll=GIJoe__Snake_Eyes
+ClassesExcludedFromAWCRoll=GIJoe__Stalker
+ClassesExcludedFromAWCRoll=GIJoe__Steeler
+ClassesExcludedFromAWCRoll=GIJoe__Zap
+ClassesExcludedFromAWCRoll=GIJoe__Shooter
